export const MOCK_ACTIVITIES = [
  // ── Musées & Expositions ────────────────────────────────────────
  {
    id: 'mock-museum-1',
    name: 'Musée du Louvre',
    category: 'museum',
    address: 'Rue de Rivoli, 75001 Paris',
    description: 'Le plus grand musée du monde : la Joconde, la Vénus de Milo, des millénaires d\'histoire',
    distance: '1.2 km',
    openingHours: 'Lun-Dim 9h-18h (fermé mar)',
    website: 'https://www.louvre.fr',
    lat: 48.8606, lng: 2.3376,
  },
  {
    id: 'mock-museum-2',
    name: 'Centre Pompidou',
    category: 'museum',
    address: 'Place Georges-Pompidou, 75004 Paris',
    description: 'Art moderne et contemporain dans un bâtiment avant-gardiste de Renzo Piano',
    distance: '0.8 km',
    openingHours: 'Mer-Lun 11h-21h',
    website: 'https://www.centrepompidou.fr',
    lat: 48.8607, lng: 2.3527,
  },
  {
    id: 'mock-museum-3',
    name: "Musée d'Orsay",
    category: 'museum',
    address: "1 Rue de la Légion d'Honneur, 75007 Paris",
    description: 'Collection impressionniste et post-impressionniste dans une somptueuse ancienne gare',
    distance: '2.1 km',
    openingHours: 'Mar-Dim 9h30-18h',
    website: 'https://www.musee-orsay.fr',
    lat: 48.8600, lng: 2.3265,
  },
  {
    id: 'mock-museum-4',
    name: 'Palais de Tokyo',
    category: 'museum',
    address: '13 Avenue du Président Wilson, 75116 Paris',
    description: 'Site de création contemporaine avec expositions immersives et événements nocturnes',
    distance: '3.5 km',
    openingHours: 'Lun-Dim 12h-0h (fermé mar)',
    lat: 48.8634, lng: 2.2974,
  },
  {
    id: 'mock-museum-5',
    name: 'Musée Rodin',
    category: 'museum',
    address: '77 Rue de Varenne, 75007 Paris',
    description: 'Le Penseur, le Baiser… les chefs-d\'œuvre de Rodin dans un hôtel particulier et son jardin',
    distance: '2.8 km',
    openingHours: 'Mar-Dim 10h-18h30',
    website: 'https://www.musee-rodin.fr',
    lat: 48.8555, lng: 2.3157,
  },

  // ── Restaurants & Gastronomie ───────────────────────────────────
  {
    id: 'mock-resto-1',
    name: 'Le Comptoir du Relais',
    category: 'restaurant',
    address: "9 Carrefour de l'Odéon, 75006 Paris",
    description: 'Bistrot parisien emblématique : cuisine bistronomique de Yves Camdeborde, terrasse animée',
    distance: '1.8 km',
    openingHours: 'Mar-Dim 12h-23h',
    lat: 48.8517, lng: 2.3388,
  },
  {
    id: 'mock-resto-2',
    name: 'Marché des Enfants Rouges',
    category: 'restaurant',
    address: '39 Rue de Bretagne, 75003 Paris',
    description: 'Le plus vieux marché couvert de Paris (1628), street food du monde entier sous les halles',
    distance: '0.9 km',
    openingHours: 'Mar-Sam 8h30-20h30, Dim 8h30-17h',
    lat: 48.8625, lng: 2.3594,
  },
  {
    id: 'mock-resto-3',
    name: 'Café de Flore',
    category: 'restaurant',
    address: '172 Boulevard Saint-Germain, 75006 Paris',
    description: 'Café mythique de Saint-Germain-des-Prés, temple des existentialistes et des gens de lettres',
    distance: '2.2 km',
    openingHours: 'Lun-Dim 7h30-1h30',
    lat: 48.8539, lng: 2.3327,
  },
  {
    id: 'mock-resto-4',
    name: 'Brasserie Lipp',
    category: 'restaurant',
    address: '151 Boulevard Saint-Germain, 75006 Paris',
    description: 'Brasserie historique depuis 1880, choucroute garnie et atmosphère parisienne immuable',
    distance: '2.0 km',
    openingHours: 'Lun-Dim 11h-1h',
    lat: 48.8540, lng: 2.3344,
  },
  {
    id: 'mock-resto-5',
    name: 'Frenchie Bar à Vins',
    category: 'restaurant',
    address: '6 Rue du Nil, 75002 Paris',
    description: 'Cuisine bistronomique créative dans la rue du Nil, produits de saison et vins naturels',
    distance: '1.4 km',
    openingHours: 'Lun-Sam 19h-0h',
    lat: 48.8642, lng: 2.3480,
  },

  // ── Nature & Balades ────────────────────────────────────────────
  {
    id: 'mock-nature-1',
    name: 'Jardin du Luxembourg',
    category: 'nature',
    address: 'Rue de Médicis, 75006 Paris',
    description: 'Magnifique jardin à la française avec fontaines, statues, ruches et parterres fleuris',
    distance: '1.5 km',
    openingHours: 'Ouvert tous les jours (horaires saisonniers)',
    lat: 48.8462, lng: 2.3372,
  },
  {
    id: 'mock-nature-2',
    name: 'Coulée Verte René-Dumont',
    category: 'nature',
    address: 'Avenue Daumesnil, 75012 Paris',
    description: 'Promenade suspendue sur les anciennes voies ferrées de la Bastille, 4.5 km de jardins',
    distance: '3.2 km',
    openingHours: 'Lun-Ven 8h-21h, Sam-Dim 9h-21h',
    lat: 48.8526, lng: 2.3762,
  },
  {
    id: 'mock-nature-3',
    name: 'Parc des Buttes-Chaumont',
    category: 'nature',
    address: 'Rue Botzaris, 75019 Paris',
    description: 'Parc romantique avec îlot rocheux, temple de la Sibylle, lac et falaises de 50 mètres',
    distance: '4.1 km',
    openingHours: 'Ouvert tous les jours 7h-21h',
    lat: 48.8795, lng: 2.3819,
  },
  {
    id: 'mock-nature-4',
    name: 'Bois de Vincennes',
    category: 'nature',
    address: 'Avenue de Saint-Maurice, 75012 Paris',
    description: 'Le plus grand espace vert de Paris : château, lac, hippodrome, zoo et jardins tropicaux',
    distance: '4.9 km',
    openingHours: 'Ouvert 24h/24',
    lat: 48.8365, lng: 2.4321,
  },
  {
    id: 'mock-nature-5',
    name: 'Berges de la Seine',
    category: 'nature',
    address: 'Voie Georges Pompidou, 75004 Paris',
    description: 'Promenade piétonne et végétalisée le long de la Seine, activités sportives et détente',
    distance: '0.6 km',
    openingHours: 'Ouvert 24h/24',
    lat: 48.8568, lng: 2.3477,
  },

  // ── Spectacles & Culture Vivante ────────────────────────────────
  {
    id: 'mock-show-1',
    name: 'Opéra Bastille',
    category: 'show',
    address: 'Place de la Bastille, 75012 Paris',
    description: "Opéra National de Paris, programmation lyrique et chorégraphique de renommée mondiale",
    distance: '2.4 km',
    openingHours: 'Billetterie Lun-Sam 11h-18h30',
    website: 'https://www.operadeparis.fr',
    lat: 48.8531, lng: 2.3694,
  },
  {
    id: 'mock-show-2',
    name: 'Comédie-Française',
    category: 'show',
    address: 'Place Colette, 75001 Paris',
    description: 'La Maison de Molière, première scène nationale fondée en 1680, répertoire classique et contemporain',
    distance: '1.1 km',
    openingHours: 'Billetterie Lun-Dim 11h-18h',
    website: 'https://www.comedie-francaise.fr',
    lat: 48.8631, lng: 2.3366,
  },
  {
    id: 'mock-show-3',
    name: 'Le Grand Rex',
    category: 'show',
    address: '1 Boulevard Poissonnière, 75002 Paris',
    description: 'Plus grande salle de cinéma d\'Europe (2800 places), Art Déco somptueux et son exceptionnel',
    distance: '1.7 km',
    openingHours: 'Ouvert tous les jours selon programmation',
    lat: 48.8700, lng: 2.3497,
  },
  {
    id: 'mock-show-4',
    name: 'Philharmonie de Paris',
    category: 'show',
    address: '221 Avenue Jean Jaurès, 75019 Paris',
    description: 'Salle de concert de renommée mondiale (2400 places), acoustique parfaite et programmation éclectique',
    distance: '4.9 km',
    website: 'https://philharmoniedeparis.fr',
    openingHours: 'Selon programmation',
    lat: 48.8894, lng: 2.3934,
  },
  {
    id: 'mock-show-5',
    name: "Théâtre du Châtelet",
    category: 'show',
    address: '2 Rue Edouard Colonne, 75001 Paris',
    description: 'Grande salle de spectacle parisienne : opéras, comédies musicales, concerts événementiels',
    distance: '1.0 km',
    openingHours: 'Billetterie Mar-Sam 11h-19h',
    lat: 48.8594, lng: 2.3484,
  },

  // ── Parcs & Loisirs ─────────────────────────────────────────────
  {
    id: 'mock-amusement-1',
    name: "Jardin d'Acclimatation",
    category: 'amusement',
    address: 'Bois de Boulogne, 75116 Paris',
    description: 'Parc d\'attractions familial avec manèges, ateliers créatifs, animaux et spectacles',
    distance: '4.6 km',
    openingHours: 'Lun-Ven 11h-19h, Sam-Dim 10h-20h',
    website: 'https://www.jardindacclimatation.fr',
    lat: 48.8762, lng: 2.2549,
  },
  {
    id: 'mock-amusement-2',
    name: 'Escape Hunt Paris',
    category: 'amusement',
    address: '11 Rue Saint-Marc, 75002 Paris',
    description: 'Escape games immersifs de 60 minutes : énigmes, indices cachés, ambiances uniques',
    distance: '1.5 km',
    openingHours: 'Lun-Dim 10h-23h',
    lat: 48.8692, lng: 2.3435,
  },
  {
    id: 'mock-amusement-3',
    name: 'Bowling de Paris',
    category: 'amusement',
    address: "Jardin d'Acclimatation, 75116 Paris",
    description: '24 pistes de bowling, billard américain, jeux d\'arcade et ambiance festive',
    distance: '4.7 km',
    openingHours: 'Lun-Dim 10h-2h',
    lat: 48.8758, lng: 2.2571,
  },
  {
    id: 'mock-amusement-4',
    name: 'Aquaboulevard de Paris',
    category: 'amusement',
    address: '4 Rue Louis Armand, 75015 Paris',
    description: 'Plus grand parc aquatique de France en intérieur : toboggans, vagues, espace tropical',
    distance: '4.2 km',
    openingHours: 'Lun-Jeu 9h-23h, Ven-Dim 8h-0h',
    website: 'https://www.aquaboulevard.fr',
    lat: 48.8336, lng: 2.2783,
  },
  {
    id: 'mock-amusement-5',
    name: 'Laser Game Évolution',
    category: 'amusement',
    address: '78 Rue du Faubourg du Temple, 75011 Paris',
    description: 'Arènes de laser game sur 600 m², scénarios variés, idéal pour groupes et anniversaires',
    distance: '2.1 km',
    openingHours: 'Lun-Dim 13h-0h',
    lat: 48.8663, lng: 2.3681,
  },
]
